README.md
README_ZH.md
examples/custom_codec/client/client.go
examples/custom_codec/protocol/pb.go
examples/custom_codec/server/server.go

Fixes #89 
---
title: 'Add a customized codec example'
labels: ''
assignees: ''
---

doc: add a customized codec example

---

eventloop_unix.go

title: ''
labels: ''
assignees: ''
---

fix: fix the bug which causes null pointer panic in loopCloseConn

---

eventloop_unix.go
eventloop_windows.go
gnet_test.go

Bug fix
Prevent closed conns from execute loops.
#194 
Maybe async funcs on `Conn` interface should declare that they will not be executed if conn is closed.

Prevent closed conn from execute any loop

---

.github/workflows/ci.yml
.github/workflows/lint.yml
acceptor_unix.go
connection_unix.go
errors/errors.go
eventloop_unix.go
internal/math.go
internal/netpoll/epoll.go
internal/netpoll/epoll_events.go
internal/netpoll/kqueue.go
internal/netpoll/kqueue_events.go
internal/netpoll/queue/lock_free_queue.go
internal/netpoll/queue/queue.go
internal/netpoll/queue/queue_test.go
pool/ringbuffer/ringbuffer.go
server_unix.go

Fixes #214
---
title: 'reduce GC pause frequency for Conn.AsyncWrite'
labels: ''
assignees: ''
---
Optimizations
Eliminate function literals and reuse structs with the help of `sync.Pool`
#214 
None

opt: reduce GC pause frequency for Conn.AsyncWrite

---

acceptor_windows.go
errors/errors.go
eventloop_windows.go

bug-fixs
windows下的 listenerRun 也就是 read 操作是一个 goroutine，而另外的 react & write 在另一个 goroutine，并且 write 出错时可能会修改 conn，这个操作必须让 read goroutine 知道，否则会导致 panic，所以做了此修改，

fix: read goroutine nil pointer panic

---

gnet_test.go
internal/socket/sockopts_posix.go
listener_unix.go
options.go

new feature
支持 so_reuseaddr 可以使得 gnet 在重启过程中，不必因为 timewait 原因而导致：bind: address already in use
ISSUES https://github.com/panjf2000/gnet/issues/266
ISSUES https://github.com/panjf2000/gnet/issues/272
PR https://github.com/panjf2000/gnet/pull/275

feat: support so_reuseaddr

---

pkg/pool/byteslice/byteslice.go
pkg/pool/byteslice/byteslice_test.go

---
title: 'zero-allocated []byte pool'
labels: 
assignees: 
---
Optimizations
**old**
```go
go test -bench=. -run=none -benchtime=3s -benchmem -memprofile=old.mem.pprof
goos: linux
goarch: amd64
pkg: github.com/panjf2000/gnet/pkg/pool/byteslice
cpu: Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
BenchmarkByteSlice/Run.N-8              51881646                63.92 ns/op           24 B/op          1 allocs/op
BenchmarkByteSlice/Run.Parallel-8       100000000               34.31 ns/op           24 B/op          1 allocs/op
PASS
ok      github.com/panjf2000/gnet/pkg/pool/byteslice    6.875s
```
------
**new**
```go
go test -bench=. -run=none -benchtime=3s -benchmem -memprofile=new.mem.pprof
goos: linux
goarch: amd64
pkg: …
```

opt: implement zero-allocated []byte pool for reusing bytes

---

client.go

The relevant closed pr: #309
The server in gnet is set `TCPNoDelay = flase` by default.
The Client in gnet use `net` package, which can be seen from https://github.com/panjf2000/gnet/blob/dev/client.go#L128
In my test, client in gnet is always set to `TCPNoDelay = true` even if you set it by `gnet.WithTCPNoDelay(gnet.TCPDelay)`, because `net` package set `TCPNoDelay = true` by default, which can be confirmed in https://github.com/golang/go/blob/master/src/net/tcpsock.go#L222

fix bug:TCP_NODELAY is always true in client

---

connection.go

Change-Id: I04c0e0b0d4ef9502195b38a545f04c9f1bc305af
---
about: Bug fix
title: 'fix the bug of the return value of conn.WriteTo'
labels: ''
assignees: ''
---
bug-fixs
conn.WriteTo should return the number of bytes actually written
https://github.com/panjf2000/gnet/issues/343
connection.go

fix the bug of the return value of conn.WriteTo

---

client.go
client_test.go
connection.go
gnet.go
gnet_test.go

net.Conn 的Close() method的function signature是Close() error, 而gnet.Conn的Close() method的function signature是Close(callback AsyncCallback) error
现在把老的函数重命名成CloseWithCallback(callback AsyncCallback)
---
name: Fix gnet.Conn not compatible with net.Conn on method Close
title: ''
labels: ''
assignees: ''
---
Yes

Fix gnet.Conn not compatible with net.Conn on method Close

---

internal/socket/tcp_socket.go
internal/socket/udp_socket.go
internal/socket/unix_socket.go

---
title: ''
labels: ''
assignees: ''
---
bug-fixes
unix socket bind should be only used in passive mode 
When using non-blocking socket as client, we should not close fd for EINPROGRESS error

fix, unix socket bind should be only used in passive mode

---

connection.go

---
about: opt
title: 'byte alignment, optimization from 144 to 136 byte'
labels: ''
assignees: ''
---
optimizations
如题，字节对齐，每创建一个 conn 结构体，可节省 8 字节
connection.go

opt: byte alignment, optimization from 144 to 136 byte

---

gnet.go
gnet_test.go

---
about: Currently with the allEngines global map multiple engines can't be created for the same protocol and port. If they are then there is no way to Stop the first engine since any subsequent engines will overwrite the entry in the allEngines map.  Changing this map and the behavior of the gnet.Stop() is a bigger change so I merely added a Stop(..) function to the Engine so that it could Stopped and not leak.  
title: ''
labels: ''
assignees: ''
---
Yes. 
Currently with the allEngines global map multiple engines can't be created for the same protocol and port. If they are then there is no way to Stop the first engine since any subsequent engines will overwrite the entry in the allEngines map.  Changing this map and the behavior of the gnet.Stop() is a bigger change …

allow creation of multiple engines on the same protocol and port

---

pkg/pool/ringbuffer/ringbuffer.go

optimizations
`bits.Len()` is optimized by the compiler as an intrinsic function, which uses an inline `BSRQ` instruction. This is significantly faster than using the for loop.
See the corresponding assembly code https://godbolt.org/z/rTebv3q7c
no
no

opt: use the std math/bits routine to count the bit length

---

eventloop.go

---
title: '修复消息多出一份的情况'
labels: ''
assignees: ''
---
version:v2.2.5
问题场景：
1. conn首次OnTraffic响应，未消费buf数据
2. 框架会复制保存buf到inboundBuffer  `_, _ = c.inboundBuffer.Write(c.buffer) `
3. 异步协程wake唤醒conn
4. 此时conn.Peek出来的buf数据是两份  (c.inboundBuffer + c.buffer)
tcp read这里修复后已经用起来了
readUDP方法应该也需要修复测试一下

修复缓冲区消息多出一份的情况

---

connection_unix.go
connection_windows.go
pkg/errors/errors.go

bug: invoke the callback whether the connection is open or not

---

internal/math/math.go

In the current implementation, if n == 0, the result is true which is incorrect.

internal/math: fix a corner case for IsPowerOfTwo

---

connection_unix.go

Also, eliminate the defer for callback in Conn.AsyncWrite with UDP

chore: add a TODO about removing the callback in Conn.AsyncWrite with UDP

---

acceptor_windows.go
engine_windows.go
listener_windows.go

opt: eliminate error logs when the service exits normally

---

.github/workflows/codeql.yml
.github/workflows/test.yml
.github/workflows/test_gc_opt.yml
.github/workflows/test_poll_opt.yml
.github/workflows/test_poll_opt_gc_opt.yml
acceptor_bsd.go
acceptor_linux.go
acceptor_unix.go
client_test.go
connection_bsd.go
connection_linux.go
eventloop_unix.go
internal/netpoll/epoll_default_poller.go
internal/netpoll/epoll_optimized_poller.go
internal/netpoll/kqueue_default_poller.go
internal/netpoll/kqueue_events.go
internal/netpoll/kqueue_optimized_poller.go
internal/netpoll/poll_data_bsd.go
internal/netpoll/poll_data_unix.go
reactor_default_bsd.go
reactor_default_linux.go

Fixes #529, along with refactoring a few code.

bug: read the remaining data after the peer wrote and closed on BSD

---

connection_unix.go

bug: fix the memory leaks of localAddr and localAddr in conn

---

acceptor_windows.go
client_test.go
client_unix.go
client_windows.go
connection_unix.go
connection_windows.go
eventloop_unix.go
eventloop_windows.go
gnet_test.go

feat: enable OnOpen for connected UDP socket

---

acceptor_unix.go
client_unix.go
connection_unix.go
engine_unix.go
eventloop_unix.go
internal/netpoll/epoll_default_poller.go
internal/netpoll/epoll_optimized_poller.go
internal/netpoll/kqueue_default_poller.go
internal/netpoll/kqueue_optimized_poller.go
internal/queue/lock_free_queue.go
internal/queue/queue.go

By prioritizing asynchronous writes.
Fixes #423

opt: mitigate the latency issue by prioritizing asynchronous writes

---

connection_unix.go

fix panic in case error not nil. m gets -1 when writes to a closed connection

bug: return 0 instead of -1 when error occurred on a write

---

README.md
README_ZH.md
acceptor_unix.go
acceptor_windows.go
client_test.go
client_unix.go
client_windows.go
connection_unix.go
connection_windows.go
engine_unix.go
engine_windows.go
eventloop_unix.go
gnet.go
gnet_test.go
internal/socket/fd_unix.go
listener_unix.go
listener_windows.go
os_unix_test.go
pkg/errors/errors.go
reactor_epoll_default.go
reactor_kqueue_default.go

feat: support multiple network addresses binding

---

gnet.go
internal/socket/sockopts_freebsd.go
internal/socket/sockopts_posix.go
internal/socket/sockopts_unix1.go

opt: only enable SO_REUSEPORT on Linux and FreeBSD

---

gnet.go

opt: don't disable SO_REUSEPORT on DragonFlyBSD

---

gnet.go
options.go

opt: disable SO_REUSEPORT on Unix domain sockets

---

connection_unix.go

bug-fixes
The code was modified at the suggestion of the author。
#615 
nothing

bug: fix Conn.Next and Conn.Peek panic On Unix

---

eventloop_unix.go

opt: close file descriptor after OnClose()

---

client_windows.go
connection_windows.go
eventloop_unix.go
eventloop_windows.go

Updates #621
Follows up #622
This PR also fixes the potential UDP socket leaks for Windows client.

opt: close file descriptor after OnClose() for UDP along with code improvement

---

client_test.go
client_unix.go
connection_windows.go
eventloop_unix.go
gnet.go
gnet_test.go
options.go

feat: support configurable I/O chunk to drain at a time in edge-triggered mode

---

connection_unix.go
connection_windows.go

bug-fixes
The code was modified at the suggestion of the author。
https://github.com/panjf2000/gnet/issues/648
nothing

bug: fix Conn.Next not safe (#648)

---

internal/socket/socket.go
internal/socket/sockopts_bsd.go
internal/socket/sockopts_darwin.go
internal/socket/sockopts_linux.go
internal/socket/sockopts_posix.go
internal/socket/tcp_socket.go
internal/socket/udp_socket.go
internal/socket/unix_socket.go
listener_unix.go
options.go
os_unix_test.go

feat: support SO_BINDTODEVICE on Linux

---

client_unix.go
client_windows.go
connection_unix.go
connection_windows.go
engine_unix.go
engine_windows.go
eventloop_unix.go
eventloop_windows.go
gnet.go
internal/netpoll/poller_epoll_default.go
internal/netpoll/poller_epoll_ultimate.go
internal/netpoll/poller_kqueue_default.go
internal/netpoll/poller_kqueue_ultimate.go
internal/queue/queue.go
pkg/logging/logger.go
pkg/pool/goroutine/goroutine.go

interface{} --> any
itf/i --> a
queue.TaskFunc --> queue.Func
queue.Run --> queue.Exec
arg --> parameter
Also, update some comments to make more sense.

chore: rename some parameters

---

connection_unix.go
connection_windows.go
eventloop_unix.go
eventloop_windows.go
pkg/buffer/linkedlist/linked_list_buffer.go

opt: eliminate the inuse eventloop.cache for idle connections

---

connection_unix.go
connection_windows.go
gnet_test.go

opt: release outboundBuffer immediately in AsyncWrite(v) if Conn is closed
